from pathlib import Path

import yaml
from click.testing import CliRunner

from omniship.cli.app import cli

WORKFLOW = """\
from omniship import Pipeline
from omniship.plugins.python import Ruff, Wheel
from omniship.plugins.github import GitHubActions, GitHubRelease, GitHubRunner

github = GitHubActions(default_runner=GitHubRunner.UBUNTU_24_04)
pipeline = Pipeline(targets=[github])

@pipeline.check
def check(stage):
    lint = stage.task(
        Ruff(),
        execution=github.job(runners=[GitHubRunner.UBUNTU_SLIM]),
    )

    @stage.task(
        name="tests",
        after=[lint],
        execution=github.job(
            runners=[
                GitHubRunner.UBUNTU_24_04,
                GitHubRunner.MACOS_15,
                GitHubRunner.WINDOWS_2025,
            ],
        ),
    )
    def tests(ctx):
        pass

@pipeline.build
def build(stage):
    stage.task(
        Wheel(),
        execution=github.job(runners=[GitHubRunner.MACOS_15]),
    )

@pipeline.ship
def ship(stage):
    stage.task(
        GitHubRelease(repository="octacity/demo", tag="v1.0.0"),
    )
"""


def test_generate_writes_valid_yaml_and_check_detects_drift(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(WORKFLOW, encoding="utf-8")
    runner = CliRunner()

    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    assert output.read_text(encoding="utf-8").startswith("# Generated by OmniShip")
    workflow_root = tmp_path / ".github" / "workflows"
    check_output = workflow_root / "check.yml"
    build_output = workflow_root / "build.yml"
    ship_output = workflow_root / "ship.yml"
    assert check_output.is_file()
    assert build_output.is_file()
    assert ship_output.is_file()
    check_actions = yaml.load(
        check_output.read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    build_actions = yaml.load(
        build_output.read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    ship_actions = yaml.load(
        ship_output.read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    assert check_actions["permissions"] == {"contents": "read"}
    assert build_actions["permissions"] == {"contents": "read"}
    assert ship_actions["permissions"] == {"contents": "read"}
    prepare_job = check_actions["jobs"]["prepare"]
    lint_job = check_actions["jobs"]["check-ruff"]
    test_job = check_actions["jobs"]["check-tests"]
    check_barrier = check_actions["jobs"]["check-complete"]
    build_job = build_actions["jobs"]["build-wheel"]
    build_barrier = build_actions["jobs"]["build-complete"]
    ship_job = ship_actions["jobs"]["ship-github-release"]
    assert lint_job["name"] == "Check · Ruff"
    assert ship_job["name"] == "Ship · GitHub Release"
    assert prepare_job["runs-on"] == "ubuntu-24.04"
    assert lint_job["runs-on"] == "ubuntu-slim"
    assert lint_job["needs"] == "prepare"
    assert test_job["runs-on"] == "${{ matrix.runner }}"
    assert test_job["needs"] == "check-ruff"
    assert test_job["strategy"] == {
        "fail-fast": "false",
        "matrix": {"runner": ["ubuntu-24.04", "macos-15", "windows-2025"]},
    }
    assert check_barrier["needs"] == "check-tests"
    assert build_job["runs-on"] == "macos-15"
    assert build_actions["jobs"]["check"] == {
        "name": "Check",
        "uses": "./.github/workflows/check.yml",
    }
    assert build_job["needs"] == "check"
    assert build_barrier["needs"] == "build-wheel"
    assert ship_job["runs-on"] == "ubuntu-24.04"
    assert ship_job["needs"] == "build"
    assert ship_job["permissions"] == {"contents": "write"}
    assert "env" not in ship_job
    steps = prepare_job["steps"]
    assert steps[0] == {
        "uses": "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
    }
    assert steps[1] == {
        "uses": "astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4"
    }
    assert {"run": "uv run omniship generate --check"} in steps
    assert {
        "name": "Run Ruff",
        "run": (
            "uv run omniship run-node --stage check --node ruff --config omniship.yaml"
        ),
    } in lint_job["steps"]
    assert {
        "name": "Run Tests",
        "run": (
            "uv run omniship run-node --stage check --node tests --config omniship.yaml"
        ),
    } in test_job["steps"]
    assert {
        "name": "Run Wheel",
        "run": (
            "uv run omniship run-node --stage build --node wheel "
            "--config omniship.yaml --export-artifacts .omniship/handoff/build-wheel"
        ),
    } in build_job["steps"]
    assert {
        "uses": "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02",
        "with": {
            "name": "omniship-build-build-wheel",
            "path": ".omniship/handoff/build-wheel",
            "include-hidden-files": "true",
        },
    } in build_job["steps"]
    assert {
        "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
        "with": {
            "pattern": "omniship-build-*",
            "path": ".omniship/imports",
        },
    } in ship_job["steps"]
    assert {
        "name": "Run GitHub Release",
        "run": (
            "uv run omniship run-node --stage ship --node github-release "
            "--config omniship.yaml --import-artifacts-root .omniship/imports"
        ),
        "env": {"GITHUB_TOKEN": "${{ github.token }}"},
    } in ship_job["steps"]
    current = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--check"],
    )
    assert current.exit_code == 0, current.output

    ship_output.write_text("changed\n", encoding="utf-8")
    drifted_actions = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--check"],
    )
    assert drifted_actions.exit_code == 1
    assert str(ship_output) in drifted_actions.output

    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--force"],
    )
    assert generated.exit_code == 0, generated.output

    output.write_text("changed\n", encoding="utf-8")
    drifted = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--check"],
    )
    assert drifted.exit_code == 1
    assert "out of date" in drifted.output


def test_generate_protects_hand_authored_yaml(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(WORKFLOW, encoding="utf-8")
    output.write_text("version: 1\n", encoding="utf-8")

    result = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert result.exit_code == 1
    assert "Refusing to overwrite" in result.output
    assert output.read_text(encoding="utf-8") == "version: 1\n"


def test_generated_imperative_pipeline_executes_with_existing_runner(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "pipeline = Pipeline()\n"
        "@pipeline.build\n"
        "def build(stage):\n"
        "    @stage.task\n"
        "    def package(ctx):\n"
        "        artifact = ctx.workspace / 'package.txt'\n"
        "        artifact.write_text('built')\n"
        "        ctx.artifacts.add(artifact)\n",
        encoding="utf-8",
    )
    runner = CliRunner()
    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output

    executed = runner.invoke(
        cli,
        ["build", "--skip-check", "-c", str(output)],
    )

    assert executed.exit_code == 0, executed.output
    assert (tmp_path / "package.txt").read_text(encoding="utf-8") == "built"


def test_cli_exports_build_artifacts_and_imports_them_for_ship(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    bundle = tmp_path / ".omniship" / "handoff"
    source.write_text(
        "from omniship import Pipeline\n"
        "pipeline = Pipeline()\n"
        "@pipeline.build\n"
        "def build(stage):\n"
        "    @stage.task\n"
        "    def package(ctx):\n"
        "        artifact = ctx.workspace / 'package.txt'\n"
        "        artifact.write_text('built')\n"
        "        ctx.artifacts.add(artifact)\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    @stage.task\n"
        "    def publish(ctx):\n"
        "        artifact = ctx.artifacts.get('package.txt')\n"
        "        if artifact is None:\n"
        "            ctx.fail('package.txt was not handed off')\n"
        "        (ctx.workspace / 'consumed.txt').write_text(artifact.path.read_text())\n",
        encoding="utf-8",
    )
    runner = CliRunner()
    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output

    built = runner.invoke(
        cli,
        [
            "build",
            "--skip-check",
            "--config",
            str(output),
            "--export-artifacts",
            str(bundle),
        ],
    )
    assert built.exit_code == 0, built.output
    (tmp_path / "package.txt").unlink()

    shipped = runner.invoke(
        cli,
        [
            "ship",
            "--skip-check",
            "--skip-build",
            "--config",
            str(output),
            "--import-artifacts",
            str(bundle),
        ],
    )

    assert shipped.exit_code == 0, shipped.output
    assert (tmp_path / "consumed.txt").read_text(encoding="utf-8") == "built"


def test_explicit_github_target_generates_actions_for_imperative_ship(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import (\n"
        "    GitHub, GitHubActions, GitHubPermission, GitHubPermissions,\n"
        ")\n"
        "github = GitHubActions()\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    @stage.task(execution=github.job(\n"
        "        permissions=GitHubPermissions(contents=GitHubPermission.WRITE),\n"
        "    ))\n"
        "    def release(ctx):\n"
        "        GitHub(ctx).release(\n"
        "            repository='0ctacity/omniship',\n"
        "            tag='v1.0.0',\n"
        "            dry_run=True,\n"
        "        )\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    actions_path = tmp_path / ".github" / "workflows" / "ship.yml"
    assert actions_path.is_file()
    actions = yaml.load(
        actions_path.read_text(encoding="utf-8"), Loader=yaml.BaseLoader
    )
    assert actions["permissions"] == {"contents": "read"}
    assert actions["jobs"]["ship-release"]["permissions"] == {"contents": "write"}


def test_generate_rejects_release_job_with_insufficient_permissions(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import (\n"
        "    GitHubActions, GitHubPermission, GitHubPermissions, GitHubRelease,\n"
        ")\n"
        "github = GitHubActions()\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    stage.task(\n"
        "        GitHubRelease(repository='0ctacity/omniship', tag='v1.0.0'),\n"
        "        execution=github.job(permissions=GitHubPermissions(\n"
        "            contents=GitHubPermission.READ,\n"
        "        )),\n"
        "    )\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 1
    assert "requires 'contents: write'" in generated.output


def test_dry_run_release_does_not_receive_write_permission(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import GitHubRelease\n"
        "pipeline = Pipeline()\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    stage.task(GitHubRelease(\n"
        "        repository='0ctacity/omniship', tag='v1.0.0', dry_run=True,\n"
        "    ))\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output
    actions = yaml.load(
        (tmp_path / ".github" / "workflows" / "ship.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )

    assert actions["permissions"] == {"contents": "read"}
    assert "permissions" not in actions["jobs"]["ship-github-release"]


def test_ship_task_without_github_permissions_does_not_receive_token(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import GitHubActions\n"
        "github = GitHubActions()\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    @stage.task\n"
        "    def publish(ctx):\n"
        "        pass\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output
    actions = yaml.load(
        (tmp_path / ".github" / "workflows" / "ship.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    run_step = actions["jobs"]["ship-publish"]["steps"][-1]

    assert "env" not in run_step


def test_run_node_executes_only_the_selected_imperative_task(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "pipeline = Pipeline()\n"
        "@pipeline.check\n"
        "def check(stage):\n"
        "    @stage.task\n"
        "    def first(ctx):\n"
        "        (ctx.workspace / 'first.txt').write_text('first')\n"
        "    @stage.task\n"
        "    def second(ctx):\n"
        "        (ctx.workspace / 'second.txt').write_text('second')\n",
        encoding="utf-8",
    )
    runner = CliRunner()
    generated = runner.invoke(cli, ["generate", "-f", str(source), "-o", str(output)])
    assert generated.exit_code == 0, generated.output

    executed = runner.invoke(
        cli,
        [
            "run-node",
            "--stage",
            "check",
            "--node",
            "first",
            "--config",
            str(output),
        ],
    )

    assert executed.exit_code == 0, executed.output
    assert (tmp_path / "first.txt").read_text(encoding="utf-8") == "first"
    assert not (tmp_path / "second.txt").exists()


def test_build_node_dependencies_download_predecessor_artifacts(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import GitHubActions, GitHubRunner\n"
        "github = GitHubActions()\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.build\n"
        "def build(stage):\n"
        "    @stage.task(execution=github.job(runners=[GitHubRunner.UBUNTU_24_04, GitHubRunner.MACOS_15]))\n"
        "    def compile(ctx):\n"
        "        pass\n"
        "    @stage.task(after=[compile])\n"
        "    def package(ctx):\n"
        "        pass\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output
    actions = yaml.load(
        (tmp_path / ".github" / "workflows" / "build.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )

    compile_job = actions["jobs"]["build-compile"]
    package_job = actions["jobs"]["build-package"]
    assert compile_job["strategy"]["matrix"]["runner"] == [
        "ubuntu-24.04",
        "macos-15",
    ]
    assert compile_job["steps"][-1]["with"]["name"] == (
        "omniship-build-build-compile-${{ matrix.runner }}"
    )
    assert package_job["needs"] == "build-compile"
    assert {
        "uses": "actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093",
        "with": {
            "pattern": "omniship-build-build-compile*",
            "path": ".omniship/imports/build-compile",
        },
    } in package_job["steps"]
    assert {
        "name": "Run Package",
        "run": (
            "uv run omniship run-node --stage build --node package "
            "--config omniship.yaml --import-artifacts-root .omniship/imports "
            "--export-artifacts .omniship/handoff/build-package"
        ),
    } in package_job["steps"]


def test_generate_writes_three_renameable_stage_workflows(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import (\n"
        "    GitHubActions, GitHubRelease, GitHubWorkflow,\n"
        ")\n"
        "from omniship.plugins.python import Ruff, Wheel\n"
        "github = GitHubActions(\n"
        "    check=GitHubWorkflow(file='ci.yml', name='CI'),\n"
        "    build=GitHubWorkflow(file='package.yml', name='Package'),\n"
        "    ship=GitHubWorkflow(file='publish.yml', name='Publish'),\n"
        ")\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.check\n"
        "def check(stage):\n"
        "    stage.task(Ruff())\n"
        "@pipeline.build\n"
        "def build(stage):\n"
        "    stage.task(Wheel())\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    stage.task(GitHubRelease(\n"
        "        repository='0ctacity/omniship', tag='v1.0.0',\n"
        "    ))\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    workflow_root = tmp_path / ".github" / "workflows"
    check = yaml.load(
        (workflow_root / "ci.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    build = yaml.load(
        (workflow_root / "package.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    ship = yaml.load(
        (workflow_root / "publish.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )

    assert check["name"] == "CI"
    assert set(check["on"]) == {"pull_request", "push", "workflow_call"}
    assert "check-ruff" in check["jobs"]
    assert "build-wheel" not in check["jobs"]

    assert build["name"] == "Package"
    assert set(build["on"]) == {"workflow_call"}
    assert build["jobs"]["check"] == {
        "name": "CI",
        "uses": "./.github/workflows/ci.yml",
    }
    assert "build-wheel" in build["jobs"]
    assert "check-ruff" not in build["jobs"]

    assert ship["name"] == "Publish"
    assert ship["on"] == {"push": {"tags": ["v*"]}}
    assert ship["jobs"]["build"] == {
        "name": "Package",
        "uses": "./.github/workflows/package.yml",
    }
    assert "check" not in ship["jobs"]
    assert ship["jobs"]["ship-github-release"]["needs"] == "build"


def test_generate_writes_typed_custom_workflow_triggers(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import (\n"
        "    GitHubActions, GitHubPullRequest, GitHubPush,\n"
        "    GitHubWorkflow, GitHubWorkflowDispatch,\n"
        ")\n"
        "github = GitHubActions(\n"
        "    check=GitHubWorkflow(\n"
        "        file='ci.yml', name='CI',\n"
        "        triggers=[\n"
        "            GitHubPullRequest(\n"
        "                branches=['main', 'develop'],\n"
        "                paths=['src/**', 'tests/**'],\n"
        "            ),\n"
        "            GitHubPush(\n"
        "                branches=['main', 'develop'],\n"
        "                paths_ignore=['docs/**'],\n"
        "            ),\n"
        "            GitHubWorkflowDispatch(),\n"
        "        ],\n"
        "    ),\n"
        "    build=GitHubWorkflow(\n"
        "        file='package.yml', name='Package', triggers=[],\n"
        "    ),\n"
        "    ship=GitHubWorkflow(\n"
        "        file='publish.yml', name='Publish',\n"
        "        triggers=[GitHubPush(tags=['release-*'])],\n"
        "    ),\n"
        ")\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.check\n"
        "def check(stage):\n"
        "    @stage.task\n"
        "    def lint(ctx):\n"
        "        pass\n"
        "@pipeline.build\n"
        "def build(stage):\n"
        "    @stage.task\n"
        "    def package(ctx):\n"
        "        pass\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    @stage.task\n"
        "    def publish(ctx):\n"
        "        pass\n",
        encoding="utf-8",
    )

    generated = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    workflow_root = tmp_path / ".github" / "workflows"
    check = yaml.load(
        (workflow_root / "ci.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    build = yaml.load(
        (workflow_root / "package.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    ship = yaml.load(
        (workflow_root / "publish.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )

    assert check["on"] == {
        "pull_request": {
            "branches": ["main", "develop"],
            "paths": ["src/**", "tests/**"],
        },
        "push": {
            "branches": ["main", "develop"],
            "paths-ignore": ["docs/**"],
        },
        "workflow_dispatch": {},
        "workflow_call": {},
    }
    assert build["on"] == {"workflow_call": {}}
    assert build["jobs"]["check"] == {
        "name": "CI",
        "uses": "./.github/workflows/ci.yml",
    }
    assert build["jobs"]["build-package"]["needs"] == "check"
    assert ship["on"] == {"push": {"tags": ["release-*"]}}
    assert ship["jobs"]["build"] == {
        "name": "Package",
        "uses": "./.github/workflows/package.yml",
    }
    assert "check" not in ship["jobs"]


def test_manual_inputs_reach_typed_and_imperative_ship_tasks(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "from omniship.plugins.github import (\n"
        "    GitHubActions, GitHubBooleanInput, GitHubRelease,\n"
        "    GitHubStringInput, GitHubWorkflow, GitHubWorkflowDispatch,\n"
        ")\n"
        "tag = GitHubStringInput(\n"
        "    'tag', description='Tag to release', required=True,\n"
        ")\n"
        "prerelease = GitHubBooleanInput(\n"
        "    'prerelease', description='Create a prerelease', default=False,\n"
        ")\n"
        "github = GitHubActions(\n"
        "    ship=GitHubWorkflow(\n"
        "        file='ship.yml', name='Ship',\n"
        "        triggers=[GitHubWorkflowDispatch(\n"
        "            inputs=[tag, prerelease],\n"
        "        )],\n"
        "    ),\n"
        ")\n"
        "pipeline = Pipeline(targets=[github])\n"
        "@pipeline.ship\n"
        "def ship(stage):\n"
        "    stage.task(GitHubRelease(\n"
        "        repository='0ctacity/omniship',\n"
        "        tag=tag, prerelease=prerelease, dry_run=True,\n"
        "    ))\n"
        "    @stage.task\n"
        "    def record_input(ctx):\n"
        "        (ctx.workspace / 'selected-tag.txt').write_text(\n"
        "            ctx.inputs['tag'], encoding='utf-8',\n"
        "        )\n",
        encoding="utf-8",
    )
    runner = CliRunner()

    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    actions = yaml.load(
        (tmp_path / ".github" / "workflows" / "ship.yml").read_text(encoding="utf-8"),
        Loader=yaml.BaseLoader,
    )
    assert actions["on"]["workflow_dispatch"]["inputs"] == {
        "tag": {
            "description": "Tag to release",
            "required": "true",
            "type": "string",
        },
        "prerelease": {
            "description": "Create a prerelease",
            "default": "false",
            "type": "boolean",
        },
    }
    release_step = actions["jobs"]["ship-github-release"]["steps"][-1]
    assert release_step["env"]["OMNISHIP_INPUTS"] == "${{ toJSON(inputs) }}"

    compiled = yaml.safe_load(output.read_text(encoding="utf-8"))
    assert compiled["ship"]["github-release"]["with"]["tag"] == {
        "$omniship_input": "tag"
    }
    assert compiled["ship"]["github-release"]["with"]["prerelease"] == {
        "$omniship_input": "prerelease"
    }

    missing = runner.invoke(
        cli,
        [
            "run-node",
            "--stage",
            "ship",
            "--node",
            "github-release",
            "--config",
            str(output),
        ],
        env={"OMNISHIP_INPUTS": ""},
    )

    assert missing.exit_code == 1
    assert "Required workflow input 'tag' was not provided" in missing.output

    released = runner.invoke(
        cli,
        [
            "run-node",
            "--stage",
            "ship",
            "--node",
            "github-release",
            "--config",
            str(output),
        ],
        env={"OMNISHIP_INPUTS": '{"tag":"v2.0.0","prerelease":true}'},
    )

    assert released.exit_code == 0, released.output

    executed = runner.invoke(
        cli,
        [
            "run-node",
            "--stage",
            "ship",
            "--node",
            "record-input",
            "--config",
            str(output),
        ],
        env={"OMNISHIP_INPUTS": '{"tag":"v2.0.0","prerelease":true}'},
    )

    assert executed.exit_code == 0, executed.output
    assert (tmp_path / "selected-tag.txt").read_text(encoding="utf-8") == "v2.0.0"
