from pathlib import Path

from click.testing import CliRunner

from omniship.cli.app import cli


WORKFLOW = """\
from omniship import Build, Check, Pipeline, Ship
from omniship.plugins.python import Ruff, Wheel
from omniship.plugins.github import GitHubRelease

pipeline = Pipeline(
    Check(Ruff()),
    Build(Wheel()),
    Ship(GitHubRelease(repository="octacity/demo", tag="v1.0.0", dry_run=True)),
)
"""


def test_generate_writes_valid_yaml_and_check_detects_drift(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(WORKFLOW, encoding="utf-8")
    runner = CliRunner()

    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert generated.exit_code == 0, generated.output
    assert output.read_text(encoding="utf-8").startswith("# Generated by OmniShip")
    current = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--check"],
    )
    assert current.exit_code == 0, current.output

    output.write_text("changed\n", encoding="utf-8")
    drifted = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output), "--check"],
    )
    assert drifted.exit_code == 1
    assert "out of date" in drifted.output


def test_generate_protects_hand_authored_yaml(tmp_path: Path) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(WORKFLOW, encoding="utf-8")
    output.write_text("version: 1\n", encoding="utf-8")

    result = CliRunner().invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )

    assert result.exit_code == 1
    assert "Refusing to overwrite" in result.output
    assert output.read_text(encoding="utf-8") == "version: 1\n"


def test_generated_imperative_pipeline_executes_with_existing_runner(
    tmp_path: Path,
) -> None:
    source = tmp_path / "workflow.py"
    output = tmp_path / "omniship.yaml"
    source.write_text(
        "from omniship import Pipeline\n"
        "pipeline = Pipeline()\n"
        "@pipeline.build\n"
        "def package(ctx):\n"
        "    artifact = ctx.workspace / 'package.txt'\n"
        "    artifact.write_text('built')\n"
        "    ctx.artifacts.add(artifact)\n",
        encoding="utf-8",
    )
    runner = CliRunner()
    generated = runner.invoke(
        cli,
        ["generate", "-f", str(source), "-o", str(output)],
    )
    assert generated.exit_code == 0, generated.output

    executed = runner.invoke(
        cli,
        ["build", "--skip-check", "-c", str(output)],
    )

    assert executed.exit_code == 0, executed.output
    assert (tmp_path / "package.txt").read_text(encoding="utf-8") == "built"
