from pathlib import Path

import pytest

from omniship import Build, Check, Pipeline, Ship
from omniship.plugins.github import GitHubRelease
from omniship.plugins.python import Pytest, Ruff, Wheel
from omniship.workflow.compiler import compile_pipeline
from omniship.workflow.errors import WorkflowError
from omniship.workflow.serializer import serialize_config


def generate_sources(ctx):
    pass


def run_tests(ctx):
    pass


def prepare_release(ctx):
    pass


def build_package(ctx):
    pass


def invalid_task():
    pass


def test_blocks_compile_to_existing_config_model(tmp_path: Path) -> None:
    pipeline = Pipeline(
        Check(Ruff(), Pytest(coverage=True, minimum_coverage=90)),
        Build(Wheel()),
        Ship(GitHubRelease(repository="octacity/omniship", tag="v1.2.3")),
    )

    config = compile_pipeline(pipeline, tmp_path / "workflow.py")

    assert list(config.check) == ["ruff", "pytest"]
    assert config.check["pytest"].uses == "python/pytest"
    assert config.check["pytest"].with_ == {
        "coverage": True,
        "minimum_coverage": 90,
    }
    assert config.build["wheel"].uses == "python/wheel"
    assert config.ship["github-release"].with_["tag"] == "v1.2.3"


def test_imperative_tasks_compile_with_function_dependencies(tmp_path: Path) -> None:
    pipeline = Pipeline()
    generate = pipeline.check(generate_sources, name="generate")
    pipeline.check(run_tests, name="test", after=[generate])

    config = compile_pipeline(pipeline, tmp_path / "workflow.py")

    assert config.check["generate"].uses == "core/python"
    assert config.check["generate"].with_ == {
        "callable": "workflow.py:generate_sources"
    }
    assert config.check["test"].needs == ["generate"]


def test_cross_stage_dependency_is_rejected(tmp_path: Path) -> None:
    pipeline = Pipeline()
    prepare = pipeline.check(prepare_release, name="prepare")
    pipeline.build(build_package, name="package", after=[prepare])

    with pytest.raises(WorkflowError, match="same stage"):
        compile_pipeline(pipeline, tmp_path / "workflow.py")


def test_invalid_task_signature_is_rejected_during_generation(tmp_path: Path) -> None:
    pipeline = Pipeline()
    pipeline.build(invalid_task)

    with pytest.raises(WorkflowError, match="exactly one context"):
        compile_pipeline(pipeline, tmp_path / "workflow.py")


def test_duplicate_block_names_are_rejected(tmp_path: Path) -> None:
    pipeline = Pipeline(Check(Ruff(), Ruff()))

    with pytest.raises(WorkflowError, match="Duplicate node name 'ruff'"):
        compile_pipeline(pipeline, tmp_path / "workflow.py")


def test_serializer_is_stable_and_uses_aliases(tmp_path: Path) -> None:
    pipeline = Pipeline(Check(Ruff()))
    config = compile_pipeline(pipeline, tmp_path / "workflow.py")

    first = serialize_config(config, source_name="workflow.py")
    second = serialize_config(config, source_name="workflow.py")

    assert first == second
    assert first.startswith("# Generated by OmniShip from workflow.py")
    assert "\nversion: 1\n" in first
    assert "with_:" not in first
    assert first.endswith("\n")
