import os
import tempfile
from pathlib import Path

import click

from omniship.config.validation import validate_config
from omniship.plugins.api import GeneratedFile
from omniship.plugins.discovery import load_plugins
from omniship.workflow import (
    compile_pipeline,
    load_workflow,
    serialize_config,
)

GENERATED_MARKER = "# Generated by OmniShip from "


@click.command("generate")
@click.option(
    "--workflow-file",
    "-f",
    default="workflow.py",
    show_default=True,
    help="Python workflow definition",
)
@click.option(
    "--output",
    "-o",
    default="omniship.yaml",
    show_default=True,
    help="Generated OmniShip pipeline destination",
)
@click.option(
    "check_only",
    "--check",
    is_flag=True,
    help="Fail if any generated file is stale",
)
@click.option("force", "--force", is_flag=True, help="Overwrite hand-authored YAML")
def generate_cmd(
    workflow_file: str,
    output: str,
    check_only: bool,
    force: bool,
) -> None:
    """Generate the OmniShip pipeline and provider CI files from Python."""
    source = Path(workflow_file).resolve()
    destination = Path(output).resolve()
    try:
        pipeline = load_workflow(source)
        config = compile_pipeline(pipeline, source)
        registry = load_plugins()
        validate_config(config, registry)
        rendered = serialize_config(config, source.name)
        generated = [GeneratedFile(destination, rendered)]
        for generator in registry.list_workflow_generators():
            generated.extend(generator.generate(config, source, destination, pipeline))
    except Exception as exc:
        if isinstance(exc, click.ClickException):
            raise
        raise click.ClickException(str(exc)) from exc

    if check_only:
        stale = [
            item.path
            for item in generated
            if not item.path.is_file()
            or item.path.read_text(encoding="utf-8") != item.content
        ]
        if stale:
            paths = ", ".join(str(path) for path in stale)
            raise click.ClickException(
                f"Generated files are out of date: {paths}; run 'omniship generate'"
            )
        for item in generated:
            click.echo(f"{item.path} is up to date")
        return

    if not force:
        protected = [
            item.path
            for item in generated
            if item.path.is_file()
            and not item.path.read_text(encoding="utf-8").startswith(GENERATED_MARKER)
        ]
        if protected:
            paths = ", ".join(str(path) for path in protected)
            raise click.ClickException(
                f"Refusing to overwrite hand-authored YAML: {paths}. Use --force."
            )

    for item in generated:
        _write_generated(item)
        click.echo(f"Generated {item.path}")


def _write_generated(item: GeneratedFile) -> None:
    item.path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=item.path.parent,
            prefix=f".{item.path.name}.",
            delete=False,
        ) as temporary:
            temporary.write(item.content)
            temporary_name = temporary.name
        os.replace(temporary_name, item.path)
    finally:
        if temporary_name and Path(temporary_name).exists():
            Path(temporary_name).unlink()
