import os
import tempfile
from pathlib import Path

import click

from omniship.config.validation import validate_config
from omniship.plugins.discovery import load_plugins
from omniship.workflow import (
    compile_pipeline,
    load_workflow,
    serialize_config,
)


GENERATED_MARKER = "# Generated by OmniShip from "


@click.command("generate")
@click.option(
    "--workflow-file",
    "-f",
    default="workflow.py",
    show_default=True,
    help="Python workflow definition",
)
@click.option(
    "--output",
    "-o",
    default="omniship.yaml",
    show_default=True,
    help="Generated YAML destination",
)
@click.option("check_only", "--check", is_flag=True, help="Fail if YAML is stale")
@click.option("force", "--force", is_flag=True, help="Overwrite hand-authored YAML")
def generate_cmd(
    workflow_file: str,
    output: str,
    check_only: bool,
    force: bool,
) -> None:
    """Generate an OmniShip YAML pipeline from Python."""
    source = Path(workflow_file).resolve()
    destination = Path(output).resolve()
    try:
        pipeline = load_workflow(source)
        config = compile_pipeline(pipeline, source)
        validate_config(config, load_plugins())
        rendered = serialize_config(config, source.name)
    except Exception as exc:
        if isinstance(exc, click.ClickException):
            raise
        raise click.ClickException(str(exc)) from exc

    existing = destination.read_text(encoding="utf-8") if destination.is_file() else None
    if check_only:
        if existing != rendered:
            raise click.ClickException(
                f"{destination} is out of date; run 'omniship generate'"
            )
        click.echo(f"{destination} is up to date")
        return

    if existing is not None and not existing.startswith(GENERATED_MARKER) and not force:
        raise click.ClickException(
            f"Refusing to overwrite hand-authored YAML: {destination}. Use --force."
        )

    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary_name: str | None = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="w",
            encoding="utf-8",
            dir=destination.parent,
            prefix=f".{destination.name}.",
            delete=False,
        ) as temporary:
            temporary.write(rendered)
            temporary_name = temporary.name
        os.replace(temporary_name, destination)
    finally:
        if temporary_name and Path(temporary_name).exists():
            Path(temporary_name).unlink()
    click.echo(f"Generated {destination}")
