import yaml

from omniship.config.models import OmniShipConfig


def serialize_config(config: OmniShipConfig, source_name: str) -> str:
    data = config.model_dump(
        by_alias=True,
        exclude_none=True,
        exclude_defaults=True,
    )
    data = {"version": config.version, **data}
    content = yaml.safe_dump(data, sort_keys=False, default_flow_style=False)
    return f"# Generated by OmniShip from {source_name}. Do not edit directly.\n{content}"
